#!/bin/sh -e

# export USER="${PWD##*-}" # TODO
export USER="drako"
export HOME="/home/$USER"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.runit/service"
if ! [ -d "$svdir" ]; then
  mkdir -p "$svdir"
fi

# Keep in mind that substitutions in here happen at string parse time, not script eval time.
exec sudo -u $USER -i <<EOF
  export XDG_RUNTIME_DIR=/run/user/$(id -u $USER)
  exec runsvdir $svdir > /home/$USER/stupid.log 2>&1
EOF
