source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/powerline.kak" defer powerline %{
  powerline-separator curve
  powerline-theme desertex
} config %{
  powerline-start
}
plug "Delapouite/kakoune-buffers"
plug "alexherbo2/auto-pairs.kak"
plug "andreyorst/smarttab.kak" defer smarttab  %{
  set-option global softtabstop 2
  set-option global tabstop 2
  set-option global indentwidth 2
} config %{
	hook global WinSetOption filetype=(rust|c|cpp|kak|sh|zig|zag|nim|java) expandtab
	hook global WinSetOption filetype=(makefile) noexpandtab
}
plug "andreyorst/fzf.kak" defer fzf %{
  set-option global fzf_window_map 'kitty @ new-window -- kak -c %val{session} -e'
  set-option global fzf_vertical_map 'kitty @ new-window -- kak -c %val{session} -e'
  set-option global fzf_horizontal_map 'kitty @ new-window -- kak -c %val{session} -e'
}

map global normal <c-p> ': fzf-mode<ret>'

set global ui_options ncurses_assistant=none
add-highlighter global/ number-lines

map global normal ^ q
map global normal <a-^> Q
map global normal q b
map global normal Q B
map global normal <a-q> <a-b>
map global normal <a-Q> <a-B>
map global normal b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
map global normal B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'

hook global WinDisplay .* info-buffers

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
  lsp-enable-window
}

hook global InsertCompletionShow .* %{
  try %{
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
  }
}
hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

hook global WinSetOption filetype=(cpp|c) %{
  clang-enable-autocomplete; clang-enable-diagnostics
}
add-highlighter global/ wrap
hook global WinSetOption filetype=(c|cpp) %{
  set window formatcmd 'clang-format -style=file'
}
hook global WinSetOption filetype=(sh|sway) %{
  set window formatcmd 'shfmt -i 2 -sr -kp'
}
hook global WinCreate [^*]* %{
  editorconfig-load
}

colorscheme desertex
