---
outputMode: active
scale: 1
background:
  red: 0.15294117647059
  green: 0.15686274509804
  blue: 0.13333333333333
  opacity: 1
widget:
  margin:
    margins:
      - 20
      - 20
      - 20
      - 20
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins:
                  - 0
                  - 88
                  - 0
                  - 32
                widget:
                  verticalLayout:
                    - date:
                        font: ~
                        font_size: 64.0
                    - clock:
                        font: ~
                        font_size: 256.0
            - verticalLayout:
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      battery:
                        font: ~
                        font_size: 24.0
                        length: 0
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      backlight:
                        device: intel_backlight
                        font: ~
                        font_size: 24.0
                        length: 0
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      pulseAudio:
                        font: ~
                        font_size: 24.0
                        length: 0
        - calendar:
            font_primary: ~
            font_secondary: ~
            font_size: 16.0
            sections: 3
        - launcher:
            font: ~
            font_size: 32.0
            length: 0
            app_opener: ""
            term_opener: ""
            url_opener: ""
fonts:
  sans: sans
  mono: mono
