---
outputMode: active
scale: 1
background:
  red: 0.0
  green: 0.0
  blue: 0.0
  opacity: 0.7
widget:
  margin:
    margins:
      - 20
      - 20
      - 20
      - 20
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins:
                  - 0
                  - 88
                  - 0
                  - 32
                widget:
                  verticalLayout:
                    - date:
                        font_size: 64.0
                    - clock:
                        font_size: 256.0
            - verticalLayout:
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      battery:
                        font_size: 24.0
                        length: 600
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      backlight:
                        device: intel_backlight
                        font_size: 24.0
                        length: 600
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      pulseAudio:
                        font_size: 24.0
                        length: 600
        - calendar:
            font_size: 16.0
            sections: 1
        - launcher:
            font_size: 24.0
            length: 1200
            app_opener: ""
            term_opener: "kitty"
            url_opener: "qutebrowser"
